config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :absences
end

app/models/absence.rb
class Absence < ApplicationRecord
  has_attached_file :document
  validates_attachment :document, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/absences_controller.rb
class AbsencesController < ApplicationController

  def show
    @absence = Absence.find(params[:id])
  end
  def new
    @absence = Absence.new
  end

  def create
      @absence = Absence.create( absence_params )
      redirect_to @absence
  end

  private

  def absence_params
      params.require(:absence).permit(:document)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/absences/new.html.erb
<h1>Register your absence</h1>

<%= form_for @absence, url: absences_path, html: { multipart: true } do |form| %>
  <%= form.file_field :document, accept: 'image/png,image/jpeg,application/pdf' %>
  <%= form.submit %>
<% end %>

app/views/absences/show.html.erb
<h2>Your absence</h2>
<% if @absence.document_content_type == "application/pdf" %>
  <%= link_to "Download", @absence.document.url %>
<% else %>
  <%= image_tag @absence.document.url  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Upload</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>